services:
  was-nest-init:
    build: .
    image: was-nest-init
    container_name: was-nest-init
    env_file:
      - .env
    ports:
      - ${EXTERNAL_PORT_HTTP}:${INTERNAL_PORT_HTTP}
    volumes:
      - ./videofile:/app/videofile
    networks:
      - threedotnet

networks:
  threedotnet:
    external: true
